create table Privilege (
   id bigint generated by default as identity,
   description varchar(255),
   primary key (id)
);

create table PrivilegeRole (
   privilegeId bigint not null,
   roleId bigint not null
);

create table Role (
   id bigint generated by default as identity,
   roleAuthority varchar(255) not null,
   primary key (id)
);

create table UserEntity (
   id bigint generated by default as identity,
   active boolean not null,
   password varchar(255),
   username varchar(255),
   primary key (id)
);

create table UserPrivilege (
   userId bigint not null,
   privilegeId bigint not null
);

alter table UserEntity 
   add constraint UK_Username unique (username);

alter table PrivilegeRole 
   add constraint UK_Privilege_Role unique (privilegeId, roleId);

alter table UserPrivilege 
   add constraint UK_User_Privilege unique (userId, privilegeId);

alter table PrivilegeRole 
   add constraint FK_PrivilegeRole_Role
   foreign key (roleId) 
   references Role;

alter table PrivilegeRole 
   add constraint FK_PrivilegeRole_Privilege
   foreign key (privilegeId) 
   references Privilege;

alter table UserPrivilege 
   add constraint FK_UserPrivilege_Privilege
   foreign key (privilegeId) 
   references Privilege;

alter table UserPrivilege 
   add constraint FK_UserPrivilege_User
   foreign key (userId) 
   references UserEntity;