create table Montadora(
    id bigint generated by default as identity,
    nome varchar(255) not null,
    primary key (id)
);

create table Modelo(
    id bigint generated by default as identity,
    montadoraId bigint not null,
    nome varchar(255) not null,
    primary key (id)
);

create table Veiculo(
    id bigint generated by default as identity,
    nome varchar(255) not null,
    modeloId bigint not null,
    dataFabricacao date not null,
    consumoCidadeKmL int not null,
    consumoRodoviaKmL int not null,
    primary key (id)
);

alter table Modelo
    add constraint FK_Modelo_Montadora
    foreign key (montadoraId)
    references Montadora;

alter table Veiculo
    add constraint FK_Veiculo_Modelo
    foreign key (modeloId)
    references Modelo;